
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-19T14:52:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce7c9359075548fbd5d89cf8757b27f3ab755bef",
 "version": "0+untagged.146.gce7c935"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
