
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-04T00:28:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e433d190147e69459d4812bddd37a5705dd58768",
 "version": "0.31.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
