# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x17mr_box_peripheral_board\"\xdc\x01\n\x06\x43onfig\x12\x0c\n\x02id\x18\x04 \x01(\t:\x00\x12\x1f\n\x14zstage_down_position\x18\x32 \x01(\x02:\x01\x30\x12 \n\x12zstage_up_position\x18\x33 \x01(\x02:\x04\x31\x30.1\x12 \n\x13pmt_control_voltage\x18\x34 \x01(\r:\x03\x39\x30\x30\x12\x1c\n\x11pmt_sampling_rate\x18\x35 \x01(\r:\x01\x31\x12\"\n\x10pmt_sys_gain_cal\x18\x36 \x01(\r:\x08\x31\x36\x37\x37\x37\x32\x31\x35\x12\x1d\n\x12pmt_sys_offset_cal\x18\x37 \x01(\r:\x01\x30')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=42
  _CONFIG._serialized_end=262
# @@protoc_insertion_point(module_scope)
